id: PFC856666
initial_creation_type: ocr
source_metadata:
  volumes:
    d1d97a0ad3a04fea83277d2e3f255212:
      base_file: v073.txt
      image_group_id: I1PD95918
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་ལས་བྱང་ཆུབ་སེམས་དཔའི་ས།
      total_pages: 1125
      volume_number: 73
